# Generated by Django 3.2.7 on 2022-04-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_or_out', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(choices=[('50_kg_bag', '50 kg Bag'), ('60_kg_bag', '60 kg Bag')], max_length=255)),
                ('loading_charges', models.IntegerField(default=0)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.party')),
            ],
        ),
    ]
