# Generated by Django 3.2.7 on 2022-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='in_or_out',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], max_length=255),
        ),
    ]
