# Generated by Django 3.2.7 on 2022-06-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_in_or_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='party',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
