# Generated by Django 3.2.7 on 2022-06-12 07:29

import billsystem.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=255)),
                ('mobile1', models.CharField(max_length=10)),
                ('mobile2', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, default='uttar pradesh', max_length=255)),
                ('state_code', models.IntegerField(blank=True, default=9)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_no', models.CharField(max_length=255)),
                ('bank_ifsc', models.CharField(max_length=255)),
                ('bank_branch', models.CharField(max_length=255)),
                ('invoices_no', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice_nos', models.JSONField(default=dict)),
                ('sign', models.ImageField(blank=True, null=True, upload_to='sign')),
            ],
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bw', models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=255)),
                ('frieght', models.IntegerField(default=0)),
                ('invoice', models.FileField(blank=True, default=None, null=True, storage=billsystem.storage_backends.OverwriteStorage(), upload_to='invoices')),
                ('expenses', models.JSONField(default=dict)),
                ('shipto', models.JSONField(default=dict)),
                ('billitems', models.JSONField(default=list)),
                ('gstdetail', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('bill_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billby')),
            ],
        ),
        migrations.CreateModel(
            name='BillTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_type', models.CharField(choices=[('MandiIn', 'MandiIn'), ('MandiOut', 'MandiOut')], max_length=255)),
                ('bill_info', models.CharField(blank=True, choices=[('bill_to', 'bill_to'), ('bill_to_ship_to', 'bill_to_ship_to')], max_length=255, null=True)),
                ('ship_details', models.JSONField(blank=True, default=dict, null=True)),
                ('party_username', models.CharField(blank=True, max_length=255, null=True)),
                ('expense', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tulai', models.FloatField(blank=True, default=0, null=True)),
                ('dharmada', models.FloatField(blank=True, default=0, null=True)),
                ('wages', models.FloatField(blank=True, default=0, null=True)),
                ('mandi_shulk', models.FloatField(blank=True, default=0, null=True)),
                ('sutli', models.FloatField(blank=True, default=0, null=True)),
                ('commision', models.FloatField(blank=True, default=0, null=True)),
                ('loading_charges', models.FloatField(blank=True, default=0, null=True)),
                ('vikas_shulk', models.FloatField(blank=True, default=0, null=True)),
                ('others', models.FloatField(blank=True, default=0, null=True)),
                ('bardana', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default='2021-01-01')),
                ('loading_date', models.DateField(default='2021-01-01')),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=255)),
                ('dara', models.JSONField(blank=True, default=list, null=True)),
                ('weight', models.FloatField()),
                ('rate', models.FloatField()),
                ('bill_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billto')),
            ],
        ),
        migrations.AddField(
            model_name='billto',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.expense'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
                ('qty', models.FloatField()),
                ('uom', models.IntegerField(blank=True, default=100)),
                ('po_number', models.CharField(blank=True, default='', max_length=255)),
                ('bill_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.billdetail')),
            ],
        ),
        migrations.AddField(
            model_name='billdetail',
            name='bill_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billto'),
        ),
    ]
