# Generated by Django 3.2.7 on 2021-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210916_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='billby',
            name='state',
            field=models.CharField(blank=True, default='uttar pradesh', max_length=255),
        ),
        migrations.AddField(
            model_name='billby',
            name='state_code',
            field=models.IntegerField(blank=True, default=9),
        ),
    ]
