# Generated by Django 3.2.7 on 2021-09-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_billby_invoices_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='bill_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.billdetail'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='rate',
            field=models.FloatField(),
        ),
    ]