# Generated by Django 3.2.7 on 2021-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billto_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='uom',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
