# Generated by Django 3.2.7 on 2021-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_billitem_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='bw',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='billdetail',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
