# Generated by Django 3.2.7 on 2021-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20210925_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='bw',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=255),
        ),
    ]
