# Generated by Django 3.2.7 on 2021-09-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_alter_billdetail_bw'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='po_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
