# Generated by Django 3.2.7 on 2021-09-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0008_billitem_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='frieght',
            field=models.IntegerField(default=0),
        ),
    ]
