# Generated by Django 3.2.7 on 2021-09-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_billdetail_frieght'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='invoice',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
