# Generated by Django 3.2.7 on 2022-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_auto_20211004_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='shipto',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dara',
            name='loading_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='dara',
            name='purchase_date',
            field=models.DateField(default='2021-01-01'),
        ),
    ]