# Generated by Django 3.2.7 on 2022-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0011_auto_20220211_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
