# Generated by Django 3.2.7 on 2022-04-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0012_billdetail_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='billby',
            name='invoice_nos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='billby',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='sign'),
        ),
    ]
