# Generated by Django 3.2.7 on 2022-06-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0013_auto_20220401_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='billto',
            name='bill_info',
            field=models.CharField(blank=True, choices=[('bill_to', 'bill_to'), ('bill_to_ship_to', 'bill_to_ship_to')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billto',
            name='expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.expense'),
        ),
        migrations.AddField(
            model_name='billto',
            name='ship_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='billto',
            name='expense',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
