# Generated by Django 3.2.7 on 2022-06-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_auto_20220611_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='billitems',
            field=models.JSONField(default=list),
        ),
    ]
