# Generated by Django 3.2.7 on 2022-06-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0014_billby_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='billdetail',
            name='billitems',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='billto',
            name='bill_info',
            field=models.CharField(blank=True, choices=[('bill_to', 'bill_to'), ('bill_to_ship_to', 'bill_to_ship_to')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billto',
            name='expenses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='billto',
            name='party_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billto',
            name='ship_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
