# Generated by Django 3.2.7 on 2022-06-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0015_billdetail_billitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='billto',
            name='party_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
