# Generated by Django 3.2.7 on 2022-06-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0016_remove_billto_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billto',
            old_name='expenses',
            new_name='expense',
        ),
    ]
