# Generated by Django 3.2.7 on 2022-06-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0017_rename_expenses_billto_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill_detail',
        ),
        migrations.RemoveField(
            model_name='dara',
            name='bill_to',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='Dara',
        ),
    ]
