# Generated by Django 3.2.7 on 2022-07-21 10:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0018_auto_20220614_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matter', ckeditor.fields.RichTextField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.billby')),
            ],
        ),
    ]
