# Generated by Django 3.2.7 on 2022-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0019_letterhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='billby',
            name='shortname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
