# Generated by Django 3.2.7 on 2022-07-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0020_billby_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='billby',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='billto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
