# Generated by Django 3.2.7 on 2022-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220705_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='pending',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
