# Generated by Django 3.2.7 on 2022-07-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_purchaseorder_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='pending',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
