# Generated by Django 3.2.7 on 2022-07-07 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_loading'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_loaded', models.FloatField(blank=True, null=True)),
                ('loading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.loading')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
            ],
        ),
    ]
