# Generated by Django 3.2.7 on 2022-07-08 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_loadingorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loading',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='loading',
            name='object_id',
        ),
        migrations.AddField(
            model_name='loading',
            name='loading_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderparty'),
        ),
        migrations.AddField(
            model_name='orderparty',
            name='brokerage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderparty',
            name='party_type',
            field=models.CharField(blank=True, choices=[('sales', 'sales'), ('purchase', 'purchase'), ('mandi-purchase', 'mandi-purchase'), ('mandi-sales', 'mandi-sales'), ('broker', 'broker')], default='both', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasebroker', to='orders.orderparty'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseparty', to='orders.orderparty'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesbroker', to='orders.orderparty'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesparty', to='orders.orderparty'),
        ),
        migrations.DeleteModel(
            name='Broker',
        ),
    ]
