# Generated by Django 3.2.7 on 2022-07-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220708_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
