# Generated by Django 3.2.7 on 2022-07-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_loading_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='loading',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
