# Generated by Django 3.2.7 on 2022-07-12 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_loading_unloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unloading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('frieght', models.FloatField()),
                ('advance_frieght', models.FloatField()),
                ('loading_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.loading')),
                ('unload_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderparty')),
            ],
        ),
        migrations.CreateModel(
            name='UnloadingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_unloaded', models.FloatField(blank=True, null=True)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder')),
                ('unloading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.unloading')),
            ],
        ),
    ]
