# Generated by Django 3.2.7 on 2022-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20220723_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadingunloading',
            name='bill_or_builty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loadingunloading',
            name='frieght_at_unloading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadingunloading',
            name='unloaded_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadingunloading',
            name='unloaded_to',
            field=models.ManyToManyField(related_name='unloaded_party', to='orders.OrderParty'),
        ),
        migrations.AddField(
            model_name='loadingunloading',
            name='unloading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loadingunloading',
            name='unloading_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loadingunloading',
            name='loading_from',
            field=models.ManyToManyField(related_name='loading_party', to='orders.OrderParty'),
        ),
    ]
