# Generated by Django 3.2.7 on 2022-08-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220728_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderparty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderparty',
            name='state',
        ),
        migrations.AlterField(
            model_name='orderparty',
            name='party_type',
            field=models.CharField(blank=True, choices=[('bilty', 'bilty'), ('sales', 'sales'), ('purchase', 'purchase'), ('mandi-purchase', 'mandi-purchase'), ('mandi-sales', 'mandi-sales'), ('broker', 'broker')], default='both', max_length=255, null=True),
        ),
    ]
